### ISSUE TITLE
Increase the supported terraform version

### ISSUE THREAD

**Issue by decentralgabe** [ceramicnetwork/terraform-aws-ceramic#17]
# Description

Running `terraform init` gives

```
|   on versions.tf line 2, in terraform:
│    2:   required_version = ">= 0.13, < 0.14"
```

# Technical Information

Is this an error with my setup, or should I downgrade to a lower Terraform version? The current version of Terraform is `1.2.7`.

**Comment by smrz2001** [comment]
Hey @decentralgabe! Hope you're doing well!!

We moved our internal infra TF scripts to TF v1 but haven't gotten to this repository yet. It's definitely on our list though. For now, will you be able to proceed with v0.13.7, which the one this module was built with? Or is that a non-starter?

**Comment by decentralgabe** [comment]
Thanks! will look forward to the newer version
